name: pull_request

on:
  pull_request


jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo ${{ github.event.pull_request.action }}
          echo ${{ github.event.pull_request.pull_request }}
          echo ${{ github.event.pull_request }}

