name: pull_request

on:
  pull_request


jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo ${{ github.event.pull_request.merged }}
          echo ${{ github.event.pull_request.html_url }}

