name: Wiki

on:
  gollum

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.repository.full_name }}.wiki
          ref: ${{ github.event.pages[0].sha }}
          fetch-depth: 2
      - name: Discord
        run: |
          content=`curl https://raw.githubusercontent.com/wiki/Masaya-Kamei/discord_webhook_test/${PAGE_NAME}.md`
          echo $content
          curl -X POST -H 'Content-type: application/json' --data \
            "{
              \"content\": \"\`\`\`diff\n+aaa\n\`\`\`\"
            }"\
            ${WEBHOOK_URL}
        env:
          ACTION: ${{ github.event.pages[0].action }}
          TITLE: ${{ github.event.pages[0].title }}
          HTML_URL: ${{ github.event.pages[0].html_url }}
          PAGE_NAME: ${{ github.event.pages[0].page_name }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
