name: Wiki

on:
  gollum

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.repository.full_name }}.wiki
          ref: ${{ github.event.pages[0].sha }}
          fetch-depth: 2
      - name: Discord
        run: |
          current=$(git rev-parse HEAD)
          prev=$(git rev-parse HEAD^)
          diff=`git diff ${prev} ${current}`
          echo ${current} ${prev} ${diff}
          curl -X POST -H 'Content-type: application/json' --data \
            "{
              \"content\": \"\`\`\`diff\n+aaa\n-bbb\n\`\`\`\"
            }"\
            ${WEBHOOK_URL}
        env:
          ACTION: ${{ github.event.pages[0].action }}
          TITLE: ${{ github.event.pages[0].title }}
          HTML_URL: ${{ github.event.pages[0].html_url }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
