name: Wiki

on:
  gollum

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Discord
        run: |
          url=${HTML_URL}/_compare/$(git rev-parse HEAD^)...$(git rev-parse HEAD)
          curl -X POST -H 'Content-type: application/json' --data \
            "{
              \"text\": \"Text Wiki ${ACTION}: ${TITLE}\n${URL}\",
              \"content\": \"Content Wiki ${ACTION}: ${TITLE}\n${URL}\"
            }"\
            ${WEBHOOK_URL}
        env:
          ACTION: ${{ github.event.pages[0].action }}
          TITLE: ${{ github.event.pages[0].title }}
          HTML_URL: ${{ github.event.pages[0].html_url }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
